services:
  data-generator_backend:
    image: data-generator_backend:DEV
    ports:
      - "9090:9090"
    environment:
      ISSUER-URI: http://127.0.0.1:8080/realms/myrealm
      JWK-SET-URI: https://127.0.0.1:8080/realms/myrealm/protocol/openid-connect/certs
      SPRING_PROFILES_ACTIVE: DEV
      DB_SERVER: 127.0.0.1
      BACKEND_USER: backend_user
      BACKEND_USER_PASSWORD: backend_mdp
      JAVA_OPTS: "-Djava.io.tmpdir=/tmp"
    security_opt:
      - no-new-privileges:true        # Empêche l'élévation de privilèges
    cap_drop: # Supprime toutes les capacités inutiles
      - ALL
    cap_add: # Ajoute uniquement ce qui est nécessaire
      - NET_BIND_SERVICE
    mem_limit: 7g                   # Limite de mémoire
    cpu_shares: 1536                   # Limite CPU (valeur relative)
    read_only: true                   # Le système de fichiers est en lecture seule
    tmpfs: # Répertoire temporaire sécurisé
       - /tmp:size=64m

networks:
  default:
    name: dataGenerator
    external: true