services:
  data-generator_backend:
    image: ${CI_REGISTRY_IMAGE}:${VERSION}
    ports:
      - "9090:9090"
    environment:
      ISSUER-URI: https://keycloak.thepaut-antoine.ovh/realms/myrealm
      JWK-SET-URI: https://keycloak.thepaut-antoine.ovh/realms/myrealm/protocol/openid-connect/certs
      SPRING_PROFILES_ACTIVE: PROD
      DB_SERVER: data-generator_postgres
      BACKEND_USER: ${BACKEND_USER}
      BACKEND_USER_PASSWORD: ${BACKEND_USER_PASSWORD}
      JAVA_OPTS: "-Djava.io.tmpdir=/tmp"
    security_opt:
      - no-new-privileges:true        # Empêche l'élévation de privilèges
    cap_drop: # Supprime toutes les capacités inutiles
      - ALL
    cap_add: # Ajoute uniquement ce qui est nécessaire
      - NET_BIND_SERVICE
    mem_limit: 7g                   # Limite de mémoire
    cpu_shares: 1536                   # Limite CPU (valeur relative)
    read_only: true                   # Le système de fichiers est en lecture seule
    tmpfs: # Répertoire temporaire sécurisé
       - /tmp:size=64m

networks:
  default:
    name: dataGenerator
    external: true