services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    ports:
      - 8080:8080
    environment:
      - KC_DB=postgres
      - KC_DB_URL=${KC_DB_URL}
      - KC_DB_USERNAME=${KC_DB_USERNAME}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_HOSTNAME=keycloak.thepaut-antoine.ovh
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_ENABLED=true
      - KC_PROXY=edge
    command:
      - start-dev
    security_opt:
      - no-new-privileges:true # Empêcher l'escalade de privilèges
    cap_drop:
      - ALL                             # Supprime toutes les capacités inutiles
    cap_add:
      - NET_BIND_SERVICE                # Ajoute uniquement la capacité de binder un port réseau
    restart: unless-stopped
    mem_limit: 4g
    cpu_shares: 1024
  
networks:
  default:
    external:
      name: dataGenerator