# note: never use the :latest tag in a production site
FROM caddy:2.8.4-alpine

# Copiez le Caddyfile dans le conteneur
COPY Caddyfile /etc/caddy/Caddyfile

# Exposez les ports nécessaires
EXPOSE 80
EXPOSE 443
