services:
  caddy:
    image: ${CI_REGISTRY_IMAGE}:${VERSION}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"

networks:
  default:
    name: dataGenerator
    external: true


volumes:
  caddy_data:
  caddy_config: